# Generated by Django 4.0.1 on 2022-02-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_comment_level_comment_lft_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
    ]
